version 2:
jobs:
  build:
    working_directory: ~/circleci-demo
    docker:
      - image: circleci/openjdk:8u171-jdk

    steps:
      - checkout

      - run: mvn dependency:go-offline
      - run: mvn test


